export const PERMISSION_CODE = {
    DASHBOARD_VIEW: 'DASHBOARD_VER',
    REPORT_SALES_VIEW: 'REPORTE_VENTAS_VER',
    REPORT_PURCHASES_VIEW: 'REPORTE_COMPRAS_VER',
    REPORT_MASSES_VIEW: 'REPORTE_MISAS_VER',
    REPORT_ECONOMIC_SUMMARY_VIEW: 'REPORTE_RESUMEN_ECONOMICO_VER',
    PERSON_VIEW: 'PERSONA_VER', PERSON_CREATE: 'PERSONA_CREAR', PERSON_EDIT: 'PERSONA_EDITAR', PERSON_STATUS: 'PERSONA_ESTADO',
    MASS_VIEW: 'MISA_VER', MASS_CREATE: 'MISA_CREAR', MASS_EDIT: 'MISA_EDITAR', MASS_CANCEL: 'MISA_ANULAR', MASS_REGISTER_WITHOUT_PAYMENT: 'MISA_REGISTRAR_SIN_PAGO', MASS_CLOSE_SCHEDULE: 'MISA_CERRAR_PROGRAMACION', MASS_REOPEN_SCHEDULE: 'MISA_REABRIR_PROGRAMACION', MASS_EXPORT: 'MISA_EXPORTAR', MASS_PRINT: 'MISA_IMPRIMIR',
    SERVICE_CATALOG_VIEW: 'SERVICIO_CATALOGO_VER', SERVICE_CATALOG_CREATE: 'SERVICIO_CATALOGO_CREAR', SERVICE_CATALOG_EDIT: 'SERVICIO_CATALOGO_EDITAR', SERVICE_CATALOG_STATUS: 'SERVICIO_CATALOGO_ESTADO',
    SERVICE_REQUEST_VIEW: 'SOLICITUD_SERVICIO_VER', SERVICE_REQUEST_CREATE: 'SOLICITUD_SERVICIO_CREAR', SERVICE_REQUEST_EDIT: 'SOLICITUD_SERVICIO_EDITAR', SERVICE_REQUEST_CANCEL: 'SOLICITUD_SERVICIO_ANULAR',
    SALE_VIEW: 'VENTA_VER', SALE_CREATE: 'VENTA_CREAR', SALE_CANCEL: 'VENTA_ANULAR', SALE_EXPORT: 'VENTA_EXPORTAR',
    PURCHASE_VIEW: 'COMPRA_VER', PURCHASE_CREATE: 'COMPRA_CREAR', PURCHASE_CANCEL: 'COMPRA_ANULAR', PURCHASE_EXPORT: 'COMPRA_EXPORTAR',
    PRODUCT_VIEW: 'PRODUCTO_VER', PRODUCT_CREATE: 'PRODUCTO_CREAR', PRODUCT_EDIT: 'PRODUCTO_EDITAR', PRODUCT_STATUS: 'PRODUCTO_ESTADO',
    INVENTORY_VIEW: 'INVENTARIO_VER', INVENTORY_MOVEMENT_CREATE: 'INVENTARIO_MOVIMIENTO_REGISTRAR',
    SUPPLIER_VIEW: 'PROVEEDOR_VER', SUPPLIER_CREATE: 'PROVEEDOR_CREAR', SUPPLIER_EDIT: 'PROVEEDOR_EDITAR', SUPPLIER_STATUS: 'PROVEEDOR_ESTADO',
    USER_VIEW: 'USUARIO_VER', USER_CREATE: 'USUARIO_CREAR', USER_EDIT: 'USUARIO_EDITAR', USER_STATUS: 'USUARIO_ESTADO', USER_RESET_PASSWORD: 'USUARIO_RESET_PASSWORD', USER_SESSION_REVOKE: 'USUARIO_SESION_REVOCAR', USER_ASSIGN_ROLES: 'USUARIO_ASIGNAR_ROLES',
    ROLE_VIEW: 'ROL_VER', ROLE_CREATE: 'ROL_CREAR', ROLE_EDIT: 'ROL_EDITAR', ROLE_STATUS: 'ROL_ESTADO', ROLE_ASSIGN_PERMISSIONS: 'ROL_ASIGNAR_PERMISOS',
    SECURITY_AUDIT_VIEW: 'AUDITORIA_SEGURIDAD_VER',
    CONFIGURATION_VIEW: 'CONFIGURACION_VER', CONFIGURATION_EDIT: 'CONFIGURACION_EDITAR',
    SACRAMENTAL_BOOK_VIEW: 'LIBRO_SACRAMENTAL_VER', SACRAMENTAL_BOOK_CREATE: 'LIBRO_SACRAMENTAL_CREAR', SACRAMENTAL_BOOK_EDIT: 'LIBRO_SACRAMENTAL_EDITAR', SACRAMENTAL_BOOK_STATE: 'LIBRO_SACRAMENTAL_ESTADO', SACRAMENTAL_BOOK_REOPEN: 'LIBRO_SACRAMENTAL_REABRIR',
    BAPTISM_VIEW: 'BAUTISMO_VER', BAPTISM_CREATE: 'BAUTISMO_CREAR', BAPTISM_EDIT: 'BAUTISMO_EDITAR',
    CONFIRMATION_VIEW: 'CONFIRMACION_VER', CONFIRMATION_CREATE: 'CONFIRMACION_CREAR', CONFIRMATION_EDIT: 'CONFIRMACION_EDITAR',
    MARRIAGE_VIEW: 'MATRIMONIO_VER', MARRIAGE_CREATE: 'MATRIMONIO_CREAR', MARRIAGE_EDIT: 'MATRIMONIO_EDITAR',
    SACRAMENTAL_CERTIFICATE_PRINT: 'CONSTANCIA_IMPRIMIR'
} as const;

export type PermissionCode = typeof PERMISSION_CODE[keyof typeof PERMISSION_CODE];
