export interface BautismoFilters { readonly idLibroSacramental?: number | null; readonly idFolioSacramental?: number | null; readonly dni?: string | null; readonly texto?: string | null; readonly fechaBautismoDesde?: string | null; readonly fechaBautismoHasta?: string | null; }
export interface BautismoListItem { readonly idBautismo:number; readonly idLibroSacramental:number; readonly numeroLibro:string; readonly idFolioSacramental:number; readonly numeroFolio:string; readonly numeroPartida:string; readonly numeroPartidaNumerica:number|null; readonly dni:string|null; readonly apellidos:string; readonly nombres:string; readonly fechaNacimiento:string|null; readonly fechaBautismo:string|null; readonly nombrePadre:string|null; readonly nombreMadre:string|null; readonly isActive:boolean; readonly rowVersion:string; }
export interface BautismoDetail extends BautismoListItem { readonly ordenFolio:number; readonly lugarNacimiento:string|null; readonly lugarBautismo:string|null; readonly padrino:string|null; readonly madrina:string|null; readonly ministro:string|null; readonly notaMarginal:string|null; readonly observaciones:string|null; readonly estadoDigitalizacion:string; readonly createdUtc:string; readonly updatedUtc:string|null; readonly createdById:number|null; readonly updatedById:number|null; }
export interface BautismoPartidaValidationRequest { readonly idLibroSacramental:number; readonly idFolioSacramental:number; readonly numeroPartida:string; readonly idBautismoExcluir?:number|null; }
export interface BautismoPartidaValidationResponse { readonly idLibroSacramental:number; readonly numeroLibro:string; readonly idFolioSacramental:number; readonly numeroFolio:string; readonly numeroPartidaIngresada:string; readonly numeroPartidaNumerica:number|null; readonly ultimaPartidaNumerica:number|null; readonly partidaEsperada:number; readonly esDuplicada:boolean; readonly requiereConfirmacion:boolean; readonly codigoValidacion:'OK'|'DUPLICADA'|'SALTO'|'FUERA_DE_SECUENCIA'|'ALFANUMERICA'|string; readonly mensaje:string; }
export interface BautismoSiguientePartidaResponse { readonly idLibroSacramental:number; readonly numeroLibro:string; readonly ultimaPartidaNumerica:number|null; readonly siguientePartidaSugerida:number; }
export interface BautismoBaseRequest { readonly idFolioSacramental:number; readonly numeroPartida:string; readonly dni:string|null; readonly apellidos:string; readonly nombres:string; readonly fechaNacimiento:string|null; readonly lugarNacimiento:string|null; readonly nombrePadre:string|null; readonly nombreMadre:string|null; readonly fechaBautismo:string|null; readonly lugarBautismo:string|null; readonly padrino:string|null; readonly madrina:string|null; readonly ministro:string|null; readonly notaMarginal:string|null; readonly observaciones:string|null; readonly confirmarSecuencia:boolean; }
export interface BautismoCreateRequest extends BautismoBaseRequest { readonly idLibroSacramental:number; }
export interface BautismoUpdateRequest extends BautismoBaseRequest { readonly rowVersion:string; }
export interface BautismoMutationResponse { readonly idBautismo:number; readonly mensaje:string; }
