export interface SacramentoCatalogItem { readonly idTipoSacramento: number; readonly codigo: string; readonly nombre: string; readonly orden: number; }
export interface EstadoFisicoCatalogItem { readonly idEstadoLibroFisico: number; readonly codigo: string; readonly nombre: string; readonly orden: number; }
export interface EstadoDigitalizacionCatalogItem { readonly idEstadoDigitalizacion: number; readonly codigo: string; readonly nombre: string; readonly orden: number; }
export interface LibroSacramentalFilters { readonly idTipoSacramento?: number | null; readonly codigoEstadoFisico?: string | null; readonly codigoEstadoDigitalizacion?: string | null; readonly numeroLibro?: string | null; readonly soloActivos?: boolean; }
export interface LibroSacramentalListItem {
    readonly idLibroSacramental: number; readonly idTipoSacramento: number; readonly codigoTipoSacramento: string; readonly tipoSacramento: string; readonly numeroLibro: string;
    readonly folioInicial: number; readonly folioFinal: number; readonly cantidadFolios: number; readonly idEstadoLibroFisico: number; readonly codigoEstadoFisico: string; readonly estadoFisico: string;
    readonly idEstadoDigitalizacion: number; readonly codigoEstadoDigitalizacion: string; readonly estadoDigitalizacion: string; readonly fechaAperturaFisica: string | null; readonly fechaCierreFisica: string | null;
    readonly ubicacionFisica: string | null; readonly observaciones: string | null; readonly digitalizacionIniciadaUtc: string | null; readonly digitalizacionCompletadaUtc: string | null;
    readonly digitalizacionReabiertaUtc: string | null; readonly isActive: boolean; readonly createdUtc: string; readonly updatedUtc: string | null; readonly foliosGenerados: number; readonly rowVersion: string;
}
export interface LibroSacramentalDetail extends LibroSacramentalListItem { readonly digitalizacionIniciadaById: number | null; readonly digitalizacionCompletadaById: number | null; readonly digitalizacionReabiertaById: number | null; readonly createdById: number | null; readonly updatedById: number | null; }
export interface FolioSacramental { readonly idFolioSacramental: number; readonly idLibroSacramental: number; readonly numeroLibro: string; readonly numeroFolio: string; readonly ordenFolio: number; readonly isActive: boolean; readonly rowVersion: string; }
export interface LibroSacramentalCreateRequest { readonly idTipoSacramento: number; readonly numeroLibro: string; readonly folioInicial: number; readonly folioFinal: number; readonly codigoEstadoFisico: string; readonly fechaAperturaFisica: string | null; readonly fechaCierreFisica: string | null; readonly ubicacionFisica: string | null; readonly observaciones: string | null; }
export interface LibroSacramentalUpdateRequest { readonly idTipoSacramento: number; readonly numeroLibro: string; readonly folioInicial: number; readonly folioFinal: number; readonly fechaAperturaFisica: string | null; readonly fechaCierreFisica: string | null; readonly ubicacionFisica: string | null; readonly observaciones: string | null; readonly rowVersion: string; }
export interface LibroSacramentalMutationResponse { readonly idLibroSacramental: number; readonly rowVersion: string; readonly mensaje: string; }
export interface LibroSacramentalCreateResponse extends LibroSacramentalMutationResponse { readonly idTipoSacramento: number; readonly codigoTipoSacramento: string; readonly tipoSacramento: string; readonly numeroLibro: string; readonly folioInicial: number; readonly folioFinal: number; readonly cantidadFolios: number; readonly estadoFisico: string; readonly estadoDigitalizacion: string; }
export interface LibroSacramentalUpdateResponse extends LibroSacramentalMutationResponse { readonly numeroLibro: string; readonly folioInicial: number; readonly folioFinal: number; readonly cantidadFolios: number; }
export interface LibroSacramentalPhysicalStatusResponse extends LibroSacramentalMutationResponse { readonly estadoFisico: string; }
export interface LibroSacramentalDigitizationStatusResponse extends LibroSacramentalMutationResponse { readonly estadoDigitalizacion: string; readonly digitalizacionIniciadaUtc: string | null; readonly digitalizacionCompletadaUtc: string | null; readonly digitalizacionReabiertaUtc: string | null; }
