import { Component, OnInit, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatSelectModule } from '@angular/material/select';
import { MatTableModule } from '@angular/material/table';
import { PERMISSION_CODE } from '../../../../core/auth/permission-code.model';
import { ConfirmActionDialog } from '../../../../shared/pages/dialogs/confirm-action-dialog/confirm-action-dialog';
import { getApiErrorMessage } from '../../../../core/feedback/api-error-message';
import { FeedbackService } from '../../../../core/feedback/feedback.service';
import { AuthStore } from '../../../auth/data-access/auth.store';
import { ConfiguracionApiService } from '../../data-access/configuracion-api.service';
import { ConfiguracionParroquia, MetodoPagoMantenimiento, TipoComprobanteMantenimiento, SerieComprobanteMantenimiento, MisaPrecioMantenimiento, MisaPrecioOpcion, CatalogoConfiguracionMantenimiento } from '../../data-access/models/configuracion-mantenimientos.models';

@Component({
    selector:'pcr-configuracion-mantenimientos',
    imports:[ReactiveFormsModule,RouterLink,MatButtonModule,MatDialogModule,MatFormFieldModule,MatIconModule,MatInputModule,MatProgressBarModule,MatSelectModule,MatTableModule],
    templateUrl:'./configuracion-mantenimientos.html',styleUrl:'./configuracion-mantenimientos.scss'
})
export class ConfiguracionMantenimientosPage implements OnInit {
    private readonly fb=inject(FormBuilder); private readonly api=inject(ConfiguracionApiService); private readonly feedback=inject(FeedbackService); private readonly auth=inject(AuthStore); private readonly dialog=inject(MatDialog);
    protected readonly loading=signal(false); protected readonly savingParroquia=signal(false); protected readonly savingPago=signal(false); protected readonly savingTipo=signal(false); protected readonly savingSerie=signal(false); protected readonly savingPrecio=signal(false); protected readonly savingCategoriaServicio=signal(false); protected readonly savingCategoriaProducto=signal(false); protected readonly savingMarcaProducto=signal(false);
    protected readonly parroquia=signal<ConfiguracionParroquia|null>(null); protected readonly metodosPago=signal<readonly MetodoPagoMantenimiento[]>([]); protected readonly tiposComprobante=signal<readonly TipoComprobanteMantenimiento[]>([]); protected readonly series=signal<readonly SerieComprobanteMantenimiento[]>([]); protected readonly preciosMisa=signal<readonly MisaPrecioMantenimiento[]>([]); protected readonly opcionesPrecio=signal<readonly MisaPrecioOpcion[]>([]); protected readonly categoriasServicio=signal<readonly CatalogoConfiguracionMantenimiento[]>([]); protected readonly categoriasProducto=signal<readonly CatalogoConfiguracionMantenimiento[]>([]); protected readonly marcasProducto=signal<readonly CatalogoConfiguracionMantenimiento[]>([]);
    protected readonly editingPago=signal<MetodoPagoMantenimiento|null>(null); protected readonly editingTipo=signal<TipoComprobanteMantenimiento|null>(null); protected readonly editingSerie=signal<SerieComprobanteMantenimiento|null>(null); protected readonly editingCategoriaServicio=signal<CatalogoConfiguracionMantenimiento|null>(null); protected readonly editingCategoriaProducto=signal<CatalogoConfiguracionMantenimiento|null>(null); protected readonly editingMarcaProducto=signal<CatalogoConfiguracionMantenimiento|null>(null);
    protected readonly paymentColumns=['codigo','nombre','estado','acciones']; protected readonly receiptColumns=['codigo','nombre','serie','ultimo','estado','acciones']; protected readonly seriesColumns=['tipo','serie','siguiente','estado','acciones']; protected readonly priceColumns=['modalidad','tipo','precio','calculo','vigencia','estado','acciones']; protected readonly catalogColumns=['codigo','nombre','uso','estado','acciones'];

    protected readonly canParishView=()=>this.auth.hasPermission(PERMISSION_CODE.CONFIG_PARISH_VIEW); protected readonly canParishEdit=()=>this.auth.hasPermission(PERMISSION_CODE.CONFIG_PARISH_EDIT);
    protected readonly canPaymentView=()=>this.auth.hasPermission(PERMISSION_CODE.PAYMENT_METHOD_VIEW); protected readonly canPaymentCreate=()=>this.auth.hasPermission(PERMISSION_CODE.PAYMENT_METHOD_CREATE); protected readonly canPaymentEdit=()=>this.auth.hasPermission(PERMISSION_CODE.PAYMENT_METHOD_EDIT); protected readonly canPaymentStatus=()=>this.auth.hasPermission(PERMISSION_CODE.PAYMENT_METHOD_STATUS);
    protected readonly canReceiptView=()=>this.auth.hasPermission(PERMISSION_CODE.RECEIPT_TYPE_VIEW); protected readonly canReceiptCreate=()=>this.auth.hasPermission(PERMISSION_CODE.RECEIPT_TYPE_CREATE); protected readonly canReceiptEdit=()=>this.auth.hasPermission(PERMISSION_CODE.RECEIPT_TYPE_EDIT); protected readonly canReceiptStatus=()=>this.auth.hasPermission(PERMISSION_CODE.RECEIPT_TYPE_STATUS);
    protected readonly canSeriesView=()=>this.auth.hasPermission(PERMISSION_CODE.RECEIPT_SERIES_VIEW); protected readonly canSeriesCreate=()=>this.auth.hasPermission(PERMISSION_CODE.RECEIPT_SERIES_CREATE); protected readonly canSeriesEditStart=()=>this.auth.hasPermission(PERMISSION_CODE.RECEIPT_SERIES_EDIT_START); protected readonly canSeriesDefault=()=>this.auth.hasPermission(PERMISSION_CODE.RECEIPT_SERIES_DEFAULT); protected readonly canSeriesStatus=()=>this.auth.hasPermission(PERMISSION_CODE.RECEIPT_SERIES_STATUS);
    protected readonly canPriceView=()=>this.auth.hasPermission(PERMISSION_CODE.MASS_PRICE_VIEW); protected readonly canPriceCreate=()=>this.auth.hasPermission(PERMISSION_CODE.MASS_PRICE_CREATE); protected readonly canPriceStatus=()=>this.auth.hasPermission(PERMISSION_CODE.MASS_PRICE_STATUS);
    protected readonly canServiceCategoryView=()=>this.auth.hasPermission(PERMISSION_CODE.SERVICE_CATEGORY_VIEW); protected readonly canServiceCategoryCreate=()=>this.auth.hasPermission(PERMISSION_CODE.SERVICE_CATEGORY_CREATE); protected readonly canServiceCategoryEdit=()=>this.auth.hasPermission(PERMISSION_CODE.SERVICE_CATEGORY_EDIT); protected readonly canServiceCategoryStatus=()=>this.auth.hasPermission(PERMISSION_CODE.SERVICE_CATEGORY_STATUS);
    protected readonly canProductCategoryView=()=>this.auth.hasPermission(PERMISSION_CODE.PRODUCT_CATEGORY_VIEW); protected readonly canProductCategoryCreate=()=>this.auth.hasPermission(PERMISSION_CODE.PRODUCT_CATEGORY_CREATE); protected readonly canProductCategoryEdit=()=>this.auth.hasPermission(PERMISSION_CODE.PRODUCT_CATEGORY_EDIT); protected readonly canProductCategoryStatus=()=>this.auth.hasPermission(PERMISSION_CODE.PRODUCT_CATEGORY_STATUS);
    protected readonly canProductBrandView=()=>this.auth.hasPermission(PERMISSION_CODE.PRODUCT_BRAND_VIEW); protected readonly canProductBrandCreate=()=>this.auth.hasPermission(PERMISSION_CODE.PRODUCT_BRAND_CREATE); protected readonly canProductBrandEdit=()=>this.auth.hasPermission(PERMISSION_CODE.PRODUCT_BRAND_EDIT); protected readonly canProductBrandStatus=()=>this.auth.hasPermission(PERMISSION_CODE.PRODUCT_BRAND_STATUS);
    protected readonly canServiceCatalogView=()=>this.auth.hasPermission(PERMISSION_CODE.SERVICE_CATALOG_VIEW);

    protected readonly parishForm=this.fb.nonNullable.group({nombreParroquia:['',[Validators.required,Validators.maxLength(250)]],lugarExpedicion:['',[Validators.required,Validators.maxLength(150)]],direccion:['',Validators.maxLength(250)],distrito:['',Validators.maxLength(100)],provincia:['',Validators.maxLength(100)],departamento:['',Validators.maxLength(100)],telefono:['',Validators.maxLength(50)],correo:['',[Validators.email,Validators.maxLength(150)]],ruc:['',[Validators.pattern(/^$|^\d{11}$/)]],nombreParroco:['',Validators.maxLength(200)]});
    protected readonly paymentForm=this.fb.nonNullable.group({codigo:['',[Validators.required,Validators.maxLength(30),Validators.pattern(/^[A-Za-z0-9_]+$/)]],nombre:['',[Validators.required,Validators.maxLength(80)]]});
    protected readonly receiptForm=this.fb.nonNullable.group({codigo:['',[Validators.required,Validators.maxLength(30),Validators.pattern(/^[A-Za-z0-9_]+$/)]],nombre:['',[Validators.required,Validators.maxLength(100)]],serieDefault:['',[Validators.required,Validators.pattern(/^[A-Za-z0-9]{4}$/)]]});
    protected readonly seriesForm=this.fb.nonNullable.group({idTipoComprobante:[0,[Validators.required,Validators.min(1)]],serie:['',[Validators.required,Validators.pattern(/^[A-Za-z0-9]{4}$/)]],primerNumero:[1,[Validators.required,Validators.min(1),Validators.max(999999999)]]});
    protected readonly priceForm=this.fb.nonNullable.group({idModalidad:[0,[Validators.required,Validators.min(1)]],idTipo:[0,[Validators.required,Validators.min(1)]],precio:[0,[Validators.required,Validators.min(.01)]],modoCalculo:['FIJO' as 'FIJO'|'POR_INTENCION',Validators.required]});
    protected readonly serviceCategoryForm=this.catalogForm();
    protected readonly productCategoryForm=this.catalogForm();
    protected readonly productBrandForm=this.catalogForm();

    ngOnInit():void{this.reload();}
    protected reload():void{this.loading.set(true);let pending=0;const done=()=>{pending--;if(pending<=0)this.loading.set(false);};const run=(allowed:boolean,fn:()=>void)=>{if(allowed){pending++;fn();}};run(this.canParishView(),()=>this.loadParroquia(done));run(this.canPaymentView(),()=>this.loadPagos(done));run(this.canReceiptView(),()=>this.loadTipos(done));run(this.canSeriesView(),()=>this.loadSeries(done));run(this.canPriceView(),()=>{this.loadPrecios(done);pending++;this.loadOpcionesPrecio(done);});run(this.canServiceCategoryView(),()=>this.loadCategoriasServicio(done));run(this.canProductCategoryView(),()=>this.loadCategoriasProducto(done));run(this.canProductBrandView(),()=>this.loadMarcasProducto(done));if(pending===0)this.loading.set(false);}

    protected saveParish():void{const current=this.parroquia();if(!this.canParishEdit()||!current||this.parishForm.invalid||this.savingParroquia()){this.parishForm.markAllAsTouched();return;}const v=this.parishForm.getRawValue();this.savingParroquia.set(true);this.api.updateParroquia({nombreParroquia:v.nombreParroquia.trim(),lugarExpedicion:v.lugarExpedicion.trim(),direccion:this.opt(v.direccion),distrito:this.opt(v.distrito),provincia:this.opt(v.provincia),departamento:this.opt(v.departamento),telefono:this.opt(v.telefono),correo:this.opt(v.correo),ruc:this.opt(v.ruc),nombreParroco:this.opt(v.nombreParroco),rowVersion:current.rowVersion}).subscribe({next:r=>{this.savingParroquia.set(false);this.applyParroquia(r);this.feedback.success('Datos de la parroquia actualizados.');},error:e=>{this.savingParroquia.set(false);this.feedback.error(getApiErrorMessage(e,'No se pudieron actualizar los datos de la parroquia.'));}});}

    protected editPayment(x:MetodoPagoMantenimiento):void{if(!this.canPaymentEdit())return;this.editingPago.set(x);this.paymentForm.reset({codigo:x.codigo,nombre:x.nombre});}
    protected cancelPaymentEdit():void{this.editingPago.set(null);this.paymentForm.reset({codigo:'',nombre:''});}
    protected normalizePaymentCode():void{this.paymentForm.controls.codigo.setValue(this.code(this.paymentForm.controls.codigo.value),{emitEvent:false});}
    protected savePayment():void{if(this.paymentForm.invalid||this.savingPago()){this.paymentForm.markAllAsTouched();return;}const v=this.paymentForm.getRawValue(),current=this.editingPago();if(!current&&!this.canPaymentCreate())return;if(current&&!this.canPaymentEdit())return;const request={codigo:this.code(v.codigo),nombre:v.nombre.trim()};const call=current?this.api.updateMetodoPago(current.idMetodoPago,{...request,rowVersion:current.rowVersion}):this.api.createMetodoPago(request);this.savingPago.set(true);call.subscribe({next:r=>{this.savingPago.set(false);this.feedback.success(r.mensaje);this.cancelPaymentEdit();this.loadPagos();},error:e=>{this.savingPago.set(false);this.feedback.error(getApiErrorMessage(e,'No se pudo guardar el método de pago.'));}});}
    protected changePaymentStatus(x:MetodoPagoMantenimiento):void{if(!this.canPaymentStatus())return;this.confirm(x.isActive?'Desactivar método de pago':'Activar método de pago',`¿Deseas ${x.isActive?'desactivar':'activar'} ${x.nombre}? Las ventas históricas no se modificarán.`,x.isActive?'Desactivar':'Activar').subscribe(ok=>{if(!ok)return;this.api.changeMetodoPagoStatus(x.idMetodoPago,{isActive:!x.isActive,rowVersion:x.rowVersion}).subscribe({next:r=>{this.feedback.success(r.mensaje);this.loadPagos();},error:e=>this.feedback.error(getApiErrorMessage(e,'No se pudo cambiar el estado.'))});});}

    protected editReceipt(x:TipoComprobanteMantenimiento):void{if(!this.canReceiptEdit())return;this.editingTipo.set(x);this.receiptForm.reset({codigo:x.codigo,nombre:x.nombre,serieDefault:x.serieDefault});}
    protected cancelReceiptEdit():void{this.editingTipo.set(null);this.receiptForm.reset({codigo:'',nombre:'',serieDefault:''});}
    protected normalizeReceipt():void{this.receiptForm.controls.codigo.setValue(this.code(this.receiptForm.controls.codigo.value),{emitEvent:false});this.receiptForm.controls.serieDefault.setValue(this.receiptForm.controls.serieDefault.value.trim().toUpperCase(),{emitEvent:false});}
    protected saveReceipt():void{if(this.receiptForm.invalid||this.savingTipo()){this.receiptForm.markAllAsTouched();return;}const v=this.receiptForm.getRawValue(),current=this.editingTipo();if(!current&&!this.canReceiptCreate())return;if(current&&!this.canReceiptEdit())return;const request={codigo:this.code(v.codigo),nombre:v.nombre.trim(),serieDefault:v.serieDefault.trim().toUpperCase()};const call=current?this.api.updateTipoComprobante(current.idTipoComprobante,{...request,rowVersion:current.rowVersion}):this.api.createTipoComprobante(request);this.savingTipo.set(true);call.subscribe({next:r=>{this.savingTipo.set(false);this.feedback.success(r.mensaje);this.cancelReceiptEdit();this.loadTipos();this.loadSeries();},error:e=>{this.savingTipo.set(false);this.feedback.error(getApiErrorMessage(e,'No se pudo guardar el tipo de comprobante.'));}});}
    protected changeReceiptStatus(x:TipoComprobanteMantenimiento):void{if(!this.canReceiptStatus())return;this.confirm(x.isActive?'Desactivar tipo de comprobante':'Activar tipo de comprobante',`¿Deseas ${x.isActive?'desactivar':'activar'} ${x.nombre}? Los comprobantes ya emitidos conservarán su historial.`,x.isActive?'Desactivar':'Activar').subscribe(ok=>{if(!ok)return;this.api.changeTipoComprobanteStatus(x.idTipoComprobante,{isActive:!x.isActive,rowVersion:x.rowVersion}).subscribe({next:r=>{this.feedback.success(r.mensaje);this.loadTipos();},error:e=>this.feedback.error(getApiErrorMessage(e,'No se pudo cambiar el estado.'))});});}

    protected editSeriesStart(x:SerieComprobanteMantenimiento):void{if(!this.canSeriesEditStart()||x.tieneMovimientos)return;this.editingSerie.set(x);this.seriesForm.reset({idTipoComprobante:x.idTipoComprobante,serie:x.serie,primerNumero:x.siguienteNumero});this.seriesForm.controls.idTipoComprobante.disable();this.seriesForm.controls.serie.disable();}
    protected cancelSeriesEdit():void{this.editingSerie.set(null);this.seriesForm.controls.idTipoComprobante.enable();this.seriesForm.controls.serie.enable();this.seriesForm.reset({idTipoComprobante:0,serie:'',primerNumero:1});}
    protected normalizeSeries():void{this.seriesForm.controls.serie.setValue(this.seriesForm.controls.serie.value.trim().toUpperCase(),{emitEvent:false});}
    protected saveSeries():void{if(this.seriesForm.invalid||this.savingSerie()){this.seriesForm.markAllAsTouched();return;}const v=this.seriesForm.getRawValue(),current=this.editingSerie();this.savingSerie.set(true);const call=current?this.api.updateSerieInicio(current.idTipoComprobante,current.serie,{primerNumero:v.primerNumero,rowVersion:current.rowVersion}):this.api.createSerieComprobante({idTipoComprobante:v.idTipoComprobante,serie:v.serie.trim().toUpperCase(),primerNumero:v.primerNumero});call.subscribe({next:r=>{this.savingSerie.set(false);this.feedback.success(r.mensaje);this.cancelSeriesEdit();this.loadSeries();this.loadTipos();},error:e=>{this.savingSerie.set(false);this.feedback.error(getApiErrorMessage(e,'No se pudo guardar la serie.'));}});}
    protected setDefaultSeries(x:SerieComprobanteMantenimiento):void{if(!this.canSeriesDefault()||x.esPredeterminada||!x.isActive)return;this.confirm('Cambiar serie predeterminada',`Las nuevas ventas de ${x.nombreTipoComprobante} utilizarán la serie ${x.serie}. ¿Continuar?`,'Usar serie').subscribe(ok=>{if(!ok)return;this.api.setSerieDefault(x.idTipoComprobante,x.serie,{tipoRowVersion:x.tipoRowVersion}).subscribe({next:r=>{this.feedback.success(r.mensaje);this.loadSeries();this.loadTipos();},error:e=>this.feedback.error(getApiErrorMessage(e,'No se pudo cambiar la serie predeterminada.'))});});}
    protected changeSeriesStatus(x:SerieComprobanteMantenimiento):void{if(!this.canSeriesStatus())return;this.api.changeSerieStatus(x.idTipoComprobante,x.serie,{isActive:!x.isActive,rowVersion:x.rowVersion}).subscribe({next:r=>{this.feedback.success(r.mensaje);this.loadSeries();},error:e=>this.feedback.error(getApiErrorMessage(e,'No se pudo cambiar el estado de la serie.'))});}

    protected savePrice():void{if(!this.canPriceCreate()||this.priceForm.invalid||this.savingPrecio()){this.priceForm.markAllAsTouched();return;}const v=this.priceForm.getRawValue();this.confirm('Registrar nueva tarifa',`La nueva tarifa reemplazará desde ahora a la tarifa vigente de esta combinación y conservará la anterior en el historial. ¿Continuar?`,'Registrar tarifa').subscribe(ok=>{if(!ok)return;this.savingPrecio.set(true);this.api.createMisaPrecio({idModalidad:v.idModalidad,idTipo:v.idTipo,precio:v.precio,modoCalculo:v.modoCalculo}).subscribe({next:r=>{this.savingPrecio.set(false);this.feedback.success(r.mensaje);this.priceForm.reset({idModalidad:0,idTipo:0,precio:0,modoCalculo:'FIJO'});this.loadPrecios();},error:e=>{this.savingPrecio.set(false);this.feedback.error(getApiErrorMessage(e,'No se pudo registrar la tarifa.'));}});});}
    protected deactivatePrice(x:MisaPrecioMantenimiento):void{if(!this.canPriceStatus()||!x.esActivo)return;this.confirm('Desactivar tarifa',`¿Deseas desactivar la tarifa ${x.nombreModalidad} / ${x.nombreTipo}? Las Misas nuevas no tendrán precio para esta combinación hasta registrar otra tarifa.`,'Desactivar').subscribe(ok=>{if(!ok)return;this.api.deactivateMisaPrecio(x.idPrecio,{rowVersion:x.rowVersion}).subscribe({next:r=>{this.feedback.success(r.mensaje);this.loadPrecios();},error:e=>this.feedback.error(getApiErrorMessage(e,'No se pudo desactivar la tarifa.'))});});}

    protected editServiceCategory(x:CatalogoConfiguracionMantenimiento):void{if(!this.canServiceCategoryEdit())return;this.editingCategoriaServicio.set(x);this.serviceCategoryForm.reset({codigo:x.codigo,nombre:x.nombre,descripcion:x.descripcion??''});}
    protected cancelServiceCategoryEdit():void{this.editingCategoriaServicio.set(null);this.serviceCategoryForm.reset({codigo:'',nombre:'',descripcion:''});}
    protected saveServiceCategory():void{const current=this.editingCategoriaServicio();if(this.serviceCategoryForm.invalid||this.savingCategoriaServicio()){this.serviceCategoryForm.markAllAsTouched();return;}if(!current&&!this.canServiceCategoryCreate())return;if(current&&!this.canServiceCategoryEdit())return;const v=this.catalogValue(this.serviceCategoryForm.getRawValue());const call=current?this.api.updateCategoriaServicio(current.id,{...v,rowVersion:current.rowVersion}):this.api.createCategoriaServicio(v);this.savingCategoriaServicio.set(true);call.subscribe({next:r=>{this.savingCategoriaServicio.set(false);this.feedback.success(r.mensaje);this.cancelServiceCategoryEdit();this.loadCategoriasServicio();},error:e=>{this.savingCategoriaServicio.set(false);this.feedback.error(getApiErrorMessage(e,'No se pudo guardar la categoría de servicio.'));}});}
    protected changeServiceCategoryStatus(x:CatalogoConfiguracionMantenimiento):void{if(!this.canServiceCategoryStatus())return;this.changeCatalogStatus(x,'categoría de servicio',(request)=>this.api.changeCategoriaServicioStatus(x.id,request),()=>this.loadCategoriasServicio());}

    protected editProductCategory(x:CatalogoConfiguracionMantenimiento):void{if(!this.canProductCategoryEdit())return;this.editingCategoriaProducto.set(x);this.productCategoryForm.reset({codigo:x.codigo,nombre:x.nombre,descripcion:x.descripcion??''});}
    protected cancelProductCategoryEdit():void{this.editingCategoriaProducto.set(null);this.productCategoryForm.reset({codigo:'',nombre:'',descripcion:''});}
    protected saveProductCategory():void{const current=this.editingCategoriaProducto();if(this.productCategoryForm.invalid||this.savingCategoriaProducto()){this.productCategoryForm.markAllAsTouched();return;}if(!current&&!this.canProductCategoryCreate())return;if(current&&!this.canProductCategoryEdit())return;const v=this.catalogValue(this.productCategoryForm.getRawValue());const call=current?this.api.updateCategoriaProducto(current.id,{...v,rowVersion:current.rowVersion}):this.api.createCategoriaProducto(v);this.savingCategoriaProducto.set(true);call.subscribe({next:r=>{this.savingCategoriaProducto.set(false);this.feedback.success(r.mensaje);this.cancelProductCategoryEdit();this.loadCategoriasProducto();},error:e=>{this.savingCategoriaProducto.set(false);this.feedback.error(getApiErrorMessage(e,'No se pudo guardar la categoría de producto.'));}});}
    protected changeProductCategoryStatus(x:CatalogoConfiguracionMantenimiento):void{if(!this.canProductCategoryStatus())return;this.changeCatalogStatus(x,'categoría de producto',(request)=>this.api.changeCategoriaProductoStatus(x.id,request),()=>this.loadCategoriasProducto());}

    protected editProductBrand(x:CatalogoConfiguracionMantenimiento):void{if(!this.canProductBrandEdit())return;this.editingMarcaProducto.set(x);this.productBrandForm.reset({codigo:x.codigo,nombre:x.nombre,descripcion:x.descripcion??''});}
    protected cancelProductBrandEdit():void{this.editingMarcaProducto.set(null);this.productBrandForm.reset({codigo:'',nombre:'',descripcion:''});}
    protected saveProductBrand():void{const current=this.editingMarcaProducto();if(this.productBrandForm.invalid||this.savingMarcaProducto()){this.productBrandForm.markAllAsTouched();return;}if(!current&&!this.canProductBrandCreate())return;if(current&&!this.canProductBrandEdit())return;const v=this.catalogValue(this.productBrandForm.getRawValue());const call=current?this.api.updateMarcaProducto(current.id,{...v,rowVersion:current.rowVersion}):this.api.createMarcaProducto(v);this.savingMarcaProducto.set(true);call.subscribe({next:r=>{this.savingMarcaProducto.set(false);this.feedback.success(r.mensaje);this.cancelProductBrandEdit();this.loadMarcasProducto();},error:e=>{this.savingMarcaProducto.set(false);this.feedback.error(getApiErrorMessage(e,'No se pudo guardar la marca.'));}});}
    protected changeProductBrandStatus(x:CatalogoConfiguracionMantenimiento):void{if(!this.canProductBrandStatus())return;this.changeCatalogStatus(x,'marca de producto',(request)=>this.api.changeMarcaProductoStatus(x.id,request),()=>this.loadMarcasProducto());}
    protected normalizeServiceCategory():void{this.serviceCategoryForm.controls.codigo.setValue(this.code(this.serviceCategoryForm.controls.codigo.value),{emitEvent:false});}
    protected normalizeProductCategory():void{this.productCategoryForm.controls.codigo.setValue(this.code(this.productCategoryForm.controls.codigo.value),{emitEvent:false});}
    protected normalizeProductBrand():void{this.productBrandForm.controls.codigo.setValue(this.code(this.productBrandForm.controls.codigo.value),{emitEvent:false});}

    protected modalidadesPrecio(){return [...new Map(this.opcionesPrecio().map(x=>[x.idModalidad,{id:x.idModalidad,nombre:x.nombreModalidad}])).values()];}
    protected tiposPrecio(){return [...new Map(this.opcionesPrecio().map(x=>[x.idTipo,{id:x.idTipo,nombre:x.nombreTipo}])).values()];}
    protected formatDate(value:string|null):string{return value?new Date(value).toLocaleString('es-PE'):'—';}

    private loadParroquia(done?:()=>void):void{this.api.getParroquia().subscribe({next:r=>{this.applyParroquia(r);done?.();},error:e=>{done?.();this.feedback.error(getApiErrorMessage(e,'No se pudieron cargar los datos de la parroquia.'));}});}
    private loadPagos(done?:()=>void):void{this.api.getMetodosPago().subscribe({next:r=>{this.metodosPago.set(r);done?.();},error:e=>{done?.();this.feedback.error(getApiErrorMessage(e,'No se pudieron cargar los métodos de pago.'));}});}
    private loadTipos(done?:()=>void):void{this.api.getTiposComprobante().subscribe({next:r=>{this.tiposComprobante.set(r);done?.();},error:e=>{done?.();this.feedback.error(getApiErrorMessage(e,'No se pudieron cargar los tipos de comprobante.'));}});}
    private loadSeries(done?:()=>void):void{if(!this.canSeriesView()){done?.();return;}this.api.getSeriesComprobante().subscribe({next:r=>{this.series.set(r);done?.();},error:e=>{done?.();this.feedback.error(getApiErrorMessage(e,'No se pudieron cargar las series.'));}});}
    private loadPrecios(done?:()=>void):void{this.api.getMisaPrecios().subscribe({next:r=>{this.preciosMisa.set(r);done?.();},error:e=>{done?.();this.feedback.error(getApiErrorMessage(e,'No se pudieron cargar las tarifas de Misas.'));}});}
    private loadOpcionesPrecio(done?:()=>void):void{this.api.getMisaPrecioOpciones().subscribe({next:r=>{this.opcionesPrecio.set(r);done?.();},error:e=>{done?.();this.feedback.error(getApiErrorMessage(e,'No se pudieron cargar las opciones de tarifas.'));}});}
    private loadCategoriasServicio(done?:()=>void):void{this.api.getCategoriasServicio().subscribe({next:r=>{this.categoriasServicio.set(r);done?.();},error:e=>{done?.();this.feedback.error(getApiErrorMessage(e,'No se pudieron cargar las categorías de servicios.'));}});}
    private loadCategoriasProducto(done?:()=>void):void{this.api.getCategoriasProducto().subscribe({next:r=>{this.categoriasProducto.set(r);done?.();},error:e=>{done?.();this.feedback.error(getApiErrorMessage(e,'No se pudieron cargar las categorías de productos.'));}});}
    private loadMarcasProducto(done?:()=>void):void{this.api.getMarcasProducto().subscribe({next:r=>{this.marcasProducto.set(r);done?.();},error:e=>{done?.();this.feedback.error(getApiErrorMessage(e,'No se pudieron cargar las marcas.'));}});}
    private applyParroquia(r:ConfiguracionParroquia):void{this.parroquia.set(r);this.parishForm.reset({nombreParroquia:r.nombreParroquia??'',lugarExpedicion:r.lugarExpedicion??'',direccion:r.direccion??'',distrito:r.distrito??'',provincia:r.provincia??'',departamento:r.departamento??'',telefono:r.telefono??'',correo:r.correo??'',ruc:r.ruc??'',nombreParroco:r.nombreParroco??''});}
    private catalogForm(){return this.fb.nonNullable.group({codigo:['',[Validators.required,Validators.maxLength(30),Validators.pattern(/^[A-Za-z0-9_]+$/)]],nombre:['',[Validators.required,Validators.maxLength(100)]],descripcion:['',Validators.maxLength(250)]});}
    private catalogValue(v:{codigo:string;nombre:string;descripcion:string}){return{codigo:this.code(v.codigo),nombre:v.nombre.trim(),descripcion:this.opt(v.descripcion)};}
    private changeCatalogStatus(x:CatalogoConfiguracionMantenimiento,label:string,call:(request:{isActive:boolean;rowVersion:string})=>ReturnType<ConfiguracionApiService['changeCategoriaServicioStatus']>,reload:()=>void):void{const next=!x.isActive;this.confirm(`${next?'Activar':'Desactivar'} ${label}`,`¿Deseas ${next?'activar':'desactivar'} ${x.nombre}?${!next&&x.tieneDependenciasActivas?' Tiene elementos activos asociados y el sistema bloqueará la operación hasta desactivarlos.':''}`,next?'Activar':'Desactivar').subscribe(ok=>{if(!ok)return;call({isActive:next,rowVersion:x.rowVersion}).subscribe({next:r=>{this.feedback.success(r.mensaje);reload();},error:e=>this.feedback.error(getApiErrorMessage(e,'No se pudo cambiar el estado.'))});});}
    private confirm(title:string,message:string,confirmText:string){return this.dialog.open(ConfirmActionDialog,{width:'min(520px, calc(100vw - 2rem))',data:{title,message,cancelText:'Cancelar',confirmText,icon:'settings'}}).afterClosed();}
    private opt(v:string):string|null{const x=v.trim();return x||null;} private code(v:string):string{return v.trim().replace(/\s+/g,'_').toUpperCase();}
}
